services:
  db:
    image: mongo:latest
    container_name: vendor-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: vendor-backend
    ports:
      - "3000:3000"
    environment:
      - URL=mongodb://db:27017/vendor_db
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: vendor-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
