name: Five Stage Pipeline

on: push

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Stage 1
        run: echo "Code Checkout"

      - name: Stage 2
        run: echo "Install Dependencies"

      - name: Stage 3
        run: echo "Build Application"

      - name: Stage 4
        run: echo "Run Tests"

      - name: Stage 5
        run: echo "Deploy Application"
